feat: save bahis version at login only
road86/bahis-serve pull request #27
Opened 2023-08-08 12:40 UTC by sharful09

## Description
Now the bahis version only will save at log in time. Instanceid column has been removed.

If the bahis desk version number is passed at log in time then save it in the table. For older bahis desk (2.2.1 and backward) application will not send the version number so save None in the table

- [ ] I have read the road86 Contribution Guide.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned at least one reviewer.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.

2023-08-08 14:22 UTC, ChasNelson1990 requested changes
LGTM - just some dead code to remove

2023-08-08 14:22 UTC, ChasNelson1990 commented on kobocat/onadata/apps/bh_module/views_forms.py
> +        # user = User.objects.get(username = username)
Can we delete these please - we don't need more dead code lol

2023-08-08 14:22 UTC, ChasNelson1990 commented on kobocat/onadata/apps/usermodule/models.py
> +    # id = models.BigIntegerField(null=False)
Can we delete this please - we don't need more dead code lol

2023-08-09 06:41 UTC, sharful09 commented on kobocat/onadata/apps/bh_module/views_forms.py
> +        # user = User.objects.get(username = username)
yes we can

2023-08-09 06:44 UTC, sharful09 commented
@ChasNelson1990 is it a good idea to save the Mac address also?

2023-08-09 06:48 UTC, sharful09 commented
Because we are getting Mac address from client request at login

2023-08-09 06:49 UTC, ChasNelson1990 commented
> @ChasNelson1990 is it a good idea to save the Mac address also?

So a lot of the codebase is set up to do that... but it was all commented out or set to null when I started working on this project. So i presume there were issues or a reason. As we don't need it right now I suggest ignoring it still?

2023-08-09 07:35 UTC, sharful09 commented
> > @ChasNelson1990 is it a good idea to save the Mac address also?
> 
> So a lot of the codebase is set up to do that... but it was all commented out or set to null when I started working on this project. So i presume there were issues or a reason. As we don't need it right now I suggest ignoring it still?

agreed, let's forget about Mac now.

2023-08-09 08:29 UTC, ChasNelson1990 reviewed
@sharful09 - wanna resolve the conflicts on this before I review it?

2023-08-09 08:40 UTC, sharful09 commented
> @sharful09 - wanna resolve the conflicts on this before I review it?

Resolved the conflicts

2023-08-09 08:44 UTC, ChasNelson1990 approved these changes

2023-08-09 08:45 UTC, merged